### ISSUE TITLE
Signup link broken

### ISSUE THREAD

**Issue by keyset** [ddd-cqrs-es/community#3]
Hello - the [heroku signup link](https://ddd-cqrs-es.herokuapp.com/) on the Readme page appears to be broken. Is there somewhere else I can request an invite?

**Comment by osoykan** [comment]
I think [this url](https://ddd-cqrs-es.slack.com/join/shared_invite/enQtNDg3NDg5MDkwMzEwLTA3MmM0ZWZkZTkwZmIzYzY2MWM5NGExOTMxYzhjMWM2YTM2NjFiZWU5NjgwY2M2YWI4MTBiNDJlOTliMmRmZjg) can work

**Comment by francescolofranco-dev** [comment]
@osoykan hey, the signup link is not active. Any chance to get a new working one?

Thanks!

**Comment by hyrmn** [comment]
Here's one that works for now @kekko1212 

https://join.slack.com/t/ddd-cqrs-es/shared_invite/enQtNDg3NDg5MDkwMzEwLWJhYjVlNTViMGEyZmI4YjdiYzRiNjFhYzEwMDNiM2Q0NWRiMDc3OTI4Njc1YjY1MzUzMTFlODkyNDY2MDEyNzM

**Comment by bartelink** [comment]
Shortened to: http://j.mp/ddd-es-cqrs
