### ISSUE TITLE
Invite link expired

### ISSUE THREAD

**Issue by alexrudd** [ddd-cqrs-es/community#6]
Hey, the invite link in the readme has expired

**Comment by yreynhout** [comment]
Seems like we can only generate invitation links that expire after 30 days (longest). This implies that we'll need to generate links at least 12 times a year, in a manual fashion ... not sure how to proceed on this.

**Comment by K0Te** [comment]
Hi,

Link has expired again.

**Comment by bukajsytlos** [comment]
is this community dead?
@bwatts
@damian
@mat-mcloughlin
@yreynhout

PS: `... not sure how to proceed on this.` I would at least set recurring event in my calendar :)

**Comment by yreynhout** [comment]
The read me has been updated with an invitation link that works (thank you @mat-mcloughlin). Hope this helps.
